# Generated by Django 3.1.3 on 2020-11-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201125_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.SlugField(default='old-post', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=200),
        ),
    ]
